"""Add operations table

Revision ID: 5e6a416b400c
Revises: 7e04c9813a7e
Create Date: 2023-02-03 01:34:38.889063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5e6a416b400c"
down_revision = "7e04c9813a7e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "operation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.String(), nullable=True),
        sa.Column("figi", sa.String(), nullable=True),
        sa.Column("instrument_type", sa.String(), nullable=True),
        sa.Column("date", sa.TIMESTAMP(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("operation")
    # ### end Alembic commands ###
