"""DB creation

Revision ID: 7e04c9813a7e
Revises: c46cb9c8067f
Create Date: 2023-02-02 03:09:12.402296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7e04c9813a7e"
down_revision = "c46cb9c8067f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
