"""New revision1

Revision ID: c46cb9c8067f
Revises: acd874435739
Create Date: 2023-02-02 03:02:30.149536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c46cb9c8067f"
down_revision = "acd874435739"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("password", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
